### ISSUE TITLE
Doesn't work with jquery CDN

### ISSUE THREAD

**Issue by krainboltgreene** [clearwater-rb/clearwater#8] opened 2015-03-27 08:19 UTC
```
A file required by "clearwater/application" wasn't found.
can't find file:
can't find file: "jquery"
```

**Comment by jgaskins** [comment] 2015-03-27 12:14
I think this is caused by assuming that you're using the `jquery-rails` gem. I haven't successfully tried it any other way yet, but I also don't want it working exclusively on Rails. Can you tell me a bit about what you're trying to do? I'll try to adapt to it.

**Comment by krainboltgreene** [comment] 2015-03-27 18:48
No, I'm using the CDN via a script element. I'm also attempting this outside of rails.

**Comment by jgaskins** [comment] 2015-03-27 19:19
Sorry, I meant the assumption that you're using the `jquery-rails` gem is what caused it. It's expecting to find jquery locally. Because Clearwater relies on jQuery, I wanted to make that an explicit dependency rather than making the user load it in, but even in Rails you have to add the gem as a dependency, so I guess removing the relevant `require` call from `clearwater/application` makes sense.

To be honest, I haven't really had a lot of success using Opal outside of Rails, so I'm not sure how to test it otherwise. What framework/library are you using?

**Comment by jgaskins** [comment] 2015-05-05 01:16
Closing since jQuery is no longer a dependency anyway.

**Closed by jgaskins** 2015-05-05 01:16 UTC
Labels: bug

**Comment by krainboltgreene** [comment] 2015-05-05 01:20
Woot!
