### ISSUE TITLE
Lifecycle hooks

### ISSUE THREAD

**Issue by krainboltgreene** [clearwater-rb/clearwater#26] opened 2015-10-19 09:18 UTC
We've discussed this over the last few weeks, so I wanted to get it in a codified area.

The idea is pretty simple: Do we want any lifecycle hooks that developers can use?

**Comment by krainboltgreene** [comment] 2015-10-19 09:22
Specifically my argument is for these hooks, as it lets the developer do some really interesting things. Here are some hooks I suggest:

  - before start (For doing compatibility checking, constraints, etc)
  - before render all (calculations, etc)
  - before render (look up trees, schedule fetches etc)
  - after render (generate dependent elements)
  - after render all (munge fetches)
  - after end (clean up)

**Comment by jgaskins** [comment] 2015-10-20 01:28
This is a duplicate of #16. :-)

**Closed by jgaskins** 2015-10-20 01:28 UTC
Labels: discussion
